name: Test

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    # This job runs on:
    # - Push to master
    # - PR creation/updates
    # - PR merge to master
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Test with Maven
        run: mvn test
